### ISSUE TITLE
Transaction ID input is limited to 8 characters

### ISSUE THREAD

**Issue by magnolia61** [JMAConsulting/biz.jmaconsulting.findpayments#1]
Great extension, it provides some search functions I think should be in CiviCRM core natively. 

Ran into a small bug though: Tried to search for a specific Transaction ID but the input is limited to 8 characters, whereas the Transaciton ID itself it not (we have longer ID;s).

**Comment by monishdeb** [comment]
Thanks @magnolia61 for your feedback, can you please check my fix - https://github.com/JMAConsulting/biz.jmaconsulting.findpayments/pull/3 ?

As per the patch, it will now inherit the html properties of financialTrxn.trxn_id column.

**Comment by monishdeb** [comment]
Closing this issue as being fixed by https://github.com/JMAConsulting/biz.jmaconsulting.findpayments/pull/3
