### ISSUE TITLE
Unknown extension key in a translation string: biz.jmaconsulting.findpayment

### ISSUE THREAD

**Issue by magnolia61** [JMAConsulting/biz.jmaconsulting.findpayments#2]
Using CiviCRM 4.7.29 with language setting in Dutch I get the following pop-up:
Unknown extension key in a translation string: biz.jmaconsulting.findpayment

**Comment by monishdeb** [comment]
@magnolia61 I have fixed this issue, can you check my PR https://github.com/JMAConsulting/biz.jmaconsulting.findpayments/pull/4 ? 

Thanks for raising this issue :)

**Comment by monishdeb** [comment]
Closing it, as the PR #4 is merged now.
